# the base config for pg-engine

Engine: 
  root_dir: root_path
  idx: 0
  output_dir: output
  #
#   Module:
#     scene:
#     material:
#     render:
#     mode: SMPL
#   #
  Material:
    osl: /home/swh/workspace/smpl-data/spher_harm/sh.osl
    # light: 
#   #
  Renderer:
    engine: BLENDER_EEVEE #CYCLES
    film_transparent: True  # hdri background transparent
    shading_system: True
    resx: 480
    resy: 640
    camera:
      radians: 8
      height: 2
      number_rank: 3
      number_per_rank: 4  
      render_list:  [9] # all :[-1]
    light:
      open: False
      radians: 7
      height: 4
    HDRI: # image lights and background
      load: True
      image: /tmp


#   #
  Model:
    selected: SMPLX
    rot: [-1.5707963267948966,0,0]
    SMPL:
      max_num: 10
      online: False
      gender: female
      smpl_dir: /home/swh/workspace/smpl-data/smpl_data
      smpl_data_filename: smpl_data.npz
      segm_overlap: segm_per_v_overlap.pkl
      J_regressor: joint_regressors.pkl
#      smpl_model_name: basicModel_f_lbs_10_207_0_v1.0.2.fbx
    SMPLX:
      max_num: 10
      onlien: False
      gender: female
      smplx_dir: /home/swh/workspace/smpl-data/smplx
      segm_overlap: segm_per_v_overlap.pkl
      J_regressor: joint_regressors.pkl
      # hand_pose: relaxed # flat or input



  input:
    bg_images:
      dir: /home/swh/workspace/smpl-data/pg-engine/bg_imgs/backgrounds
      txt: test_img.txt
      data: test
      
    uv_textures:
      clothing_option: nongrey
      dir: /home/swh/workspace/smpl-data/smpl_data/textures
      data: female
      txt: female_all.txt

  output:
    format: video # image
    segmentation: True
    depth: True
    normal: True
    fg: True
    gtflow: True
    labels:
      dir_name: labelInfo
      gender: True
      joints2D: True
      joints3D: True
      pose: False
      shape: False
      camera: True
    

    
