# the base config for pg-engine

Engine: 
  root_dir: root_path
  idx: 0
  output_dir: test_knn
  #
#   Module:
#     scene:
#     material:
#     render:
#     mode: SMPL
#   #
  Material:
    osl: /home/swh/work_space/smpl-data/spher_harm/sh.osl
    # light: 
#   #
  Renderer:
    engine: CYCLES
    resx: 480
    resy: 640
    camera:
      cam_dist: 8.0
      cam_height: 1.0
      zrot_euler: 0.0 # 0 45 90 135 180 225 270 315
      cam_dist_range: [7,8]
      cam_height_range: [-5,-5]

#   #
  Model:
    selected: SMPLX
    SMPL:
      max_num: 10
      online: False
      gender: female
      smpl_dir: /home/swh/work_space/smpl-data/smpl_data
      smpl_data_filename: smpl_data.npz
      segm_overlap: segm_per_v_overlap.pkl
      J_regressor: joint_regressors.pkl
#      smpl_model_name: basicModel_f_lbs_10_207_0_v1.0.2.fbx
    SMPLX:
      max_num: 10
      onlien: False
      gender: female
      smplx_dir: /home/swh/work_space/smpl-data/smplx
      segm_overlap: segm_per_v_overlap.pkl
      J_regressor: joint_regressors.pkl
      # hand_pose: relaxed # flat or input



  input:
    bg_images:
      dir: /home/swh/work_space/smpl-data/pg-engine/bg_imgs/backgrounds
      txt: test_img.txt
      data: test
      
    uv_textures:
      clothing_option: nongrey
      dir: /home/swh/work_space/smpl-data/smpl_data/textures
      data: female
      txt: female_all.txt

  output:
    format: video # image
    root_dir: output
    segmentation: True
    depth: True
    normal: True
    fg: True
    gtflow: True
    labels:
      format: .mat
      output_name: label_info
      bg: True
      cloth: True
      gender: True
      joints2D: True
      joints3D: True
      pose: False
      shape: False
      source: False
      zrot_euler: False
      light: False
      cam_height: False
      cam_dist: False
    

    
